const classlists = [
{
      "id": 1001,
     "title": "Mathematics",
     "description": "Provides additional support and instruction to help children develop a strong foundation in math concepts, problem-solving, and analytical skills.",
     "location": "Dubai, Barsha 1",
     "price": 500,
     "image": "img/math.jpg",
     "availableInventory": 5,
     "rating": 5,
 },
 {
     "id": 1002,
     "title": "Art",
     "description": "Encourages creativity and imagination through painting, drawing, and crafting.",
     "location": "Dubai, Marina Towers",
     "price": 300,
     "image": "img/Art.jpg",
     "availableInventory": 5,
     "rating": 5,
 },
 {
     "id": 1003,
     "title": "Music",
     "description": "Introduces children to music theory, instruments, and singing to improve their musical abilities.",
     "location": "Dubai, JBR",
     "price": 300,
     "image": "img/music.jpg",
     "availableInventory": 5,
     "rating": 5,
 },
 {
     "id": 1004,
     "title": "Sports Clubs",
     "description": "Teaches kids the importance of team work while maintaining an active lifestyle",
     "location": "Dubai, JBR",
     "price": 300,
     "image": "img/sport.png",
     "availableInventory": 5,
     "rating": 4,
 },
 {
    "id": 1005,
    "title": "Coding",
    "description": "Teaches kids the basics of coding and computer programming, preparing them for future technology-related careers.",
    "location": "Dubai, Marina",
    "price": 500,
    "image": "img/coding.jpg",
    "availableInventory": 5,
    "rating": 5,
},
{
    "id": 1006,
    "title": "Language Classes",
    "description": "Learn a new language such as Spanish, French, or Mandarin through interactive lessons and activities.",
    "location": "Dubai, JBR",
    "price": 350,
    "image": "img/language.jpg",
    "availableInventory": 5,
    "rating": 5,
},
{
    "id": 1007,
    "title": "Drama",
    "description": "Build confidence and acting skills through improvisation, scene work, and theatre games.",
    "location": "Dubai, Marina",
    "price": 350,
    "image": "img/drama.jpg",
    "availableInventory": 5,
    "rating": 3,
},
{
    "id": 1008,
    "title": "Cooking lessons",
    "description": "Explore the culinary world by learning how to prepare and cook delicious and healthy meals.",
    "location": "Dubai, Barsha 1",
    "price": 300,
    "image": "img/cooking.jpg",
    "availableInventory": 5,
    "rating": 4,
},
{
    "id": 1009,
    "title": "Science",
    "description": "Conduct experiments and explore scientific concepts through hands-on activities and projects.",
    "location": "Dubai, Barsha 1",
    "price": 400,
    "image": "img/science.jpg",
    "availableInventory": 5,
    "rating": 5,
},
{
    "id": 1010,
    "title": "Robotics",
    "description": "build and program robots using LEGO kits to explore engineering and technology concepts.",
    "location": "Dubai, JBR",
    "price": 500,
    "image": "img/robotics.jpg",
    "availableInventory": 5,
    "rating": 5,
} 
 ]
 